- name: Install Node Exporter on Web Server (non-Docker)
  hosts: web
  become: yes
  tasks:

    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /sbin/nologin
        system: yes

    - name: Download Node Exporter tarball
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/
        remote_src: yes
        creates: /opt/node_exporter-1.8.1.linux-amd64/node_exporter

    - name: Create symlink for node_exporter binary
      file:
        src: /opt/node_exporter-1.8.1.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        state: link

    - name: Create systemd service for Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter --web.listen-address=:9100

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started


- name: Install Docker on Monitoring Server
  hosts: monitoring
  become: yes
  tasks:

    - name: Install Docker prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update_cache: yes

    - name: Install Docker
      shell: curl -fsSL https://get.docker.com | sh

    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes


- name: Deploy Prometheus and Grafana (Docker) on Monitoring Server
  hosts: monitoring
  become: yes
  tasks:

    - name: Create Prometheus config directory
      file:
        path: /opt/prometheus
        state: directory

    - name: Copy Prometheus config file
      copy:
        dest: /opt/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 5s
          scrape_configs:
            - job_name: "web-server"
              static_configs:
                - targets:
                    - "10.0.0.5:9100"

    - name: Run Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "9090:9090"
        volumes:
          - "/opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

    - name: Run Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "3000:3000"
